name: Deploy everything to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build_backend_and_infra:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend_version:
              - 'backend/version.txt'

      - name: Set up JDK
        if: steps.filter.outputs.backend_version == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        if: steps.filter.outputs.backend_version == 'true'
        run: chmod +x gradlew
        working-directory: backend

      - name: Run Gradle build
        if: steps.filter.outputs.backend_version == 'true'
        working-directory: backend
        run: ./gradlew packageForEb
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra

  upload_frontend:
    runs-on: ubuntu-latest
    needs: build_backend_and_infra

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Set up Node.js 22
        if: steps.filter.outputs.frontend == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      
      - name: Install dependencies
        if: steps.filter.outputs.frontend == 'true'
        working-directory: frontend
        run: yarn install
      
      - name: Build frontend
        if: steps.filter.outputs.frontend == 'true'
        working-directory: frontend
        run: yarn build
        env:
          VITE_API_URL: http://cloud-assignment-photo-backend.eu-central-1.elasticbeanstalk.com
      
      - name: Upload to S3
        if: steps.filter.outputs.frontend == 'true'
        working-directory: frontend
        run: aws s3 sync ./dist s3://photo-site-frontend-bucket --delete